const events = [
  {
    id: 3,
    image: "./Movienight.png",
    date: new Date("2026-04-22T19:00:00"),
    title: "Movie night",
    start_time: "19:00",
    end_time: "23:00",
    type: "cultuur",
    location: "Campus Schoonmeersen",
    description:
      "Gezellige filmavond met snacks en drankjes. Stem mee welke film we kijken.",
  },
  {
    id: 4,
    image: "./Bowling.png",
    date: new Date("2026-05-05T14:00:00"),
    title: "Bowling",
    start_time: "14:00",
    end_time: "18:00",
    type: "sport",
    location: "O'Learys",
    description:
      "We gaan samen bowlen bij O'Learys. Iedereen welkom, ervaring niet nodig.",
  },
  {
    id: 5,
    image: "./Schaaktoernooi.png",
    date: new Date("2026-06-01T13:00:00"),
    title: "Schaaktoernooi",
    start_time: "13:00",
    end_time: "18:00",
    type: "sport",
    location: "Comic Sans",
    description:
      "Test je strategie en speel mee in ons schaaktoernooi. Leuke sfeer gegarandeerd.",
  },
  {
    id: 6,
    image: "./Tetristoernooi.png",
    date: new Date("2026-06-13T13:00:00"),
    title: "Tetris toernooi",
    start_time: "13:00",
    end_time: "18:00",
    type: "sport",
    location: "Comic Sans",
    description: "Retro gaming namiddag met een competitief Tetris toernooi.",
  },
  {
    id: 7,
    image: "./Movienight.png",
    date: new Date("2026-07-16T19:00:00"),
    title: "Movie night",
    start_time: "19:00",
    end_time: "23:00",
    type: "cultuur",
    location: "Campus Schoonmeersen",
    description:
      "Ontspan met een filmavond samen met de vereniging. Snacks voorzien.",
  },
  {
    id: 8,
    image: "./Bowling.png",
    date: new Date("2026-07-28T14:00:00"),
    title: "Bowling",
    start_time: "14:00",
    end_time: "18:00",
    type: "sport",
    location: "O'Learys",
    description:
      "Een namiddag vol bowling en gezelligheid. Kom alleen of met vrienden.",
  },
  {
    id: 9,
    image: "./Schaaktoernooi.png",
    date: new Date("2026-08-12T13:00:00"),
    title: "Schaaktoernooi",
    start_time: "13:00",
    end_time: "18:00",
    type: "sport",
    location: "Comic Sans",
    description:
      "Schaaktoernooi voor alle niveaus. Speel mee en maak kans op een prijs.",
  },
  {
    id: 10,
    image: "./Tetristoernooi.png",
    date: new Date("2026-08-25T13:00:00"),
    title: "Tetris toernooi",
    start_time: "13:00",
    end_time: "18:00",
    type: "sport",
    location: "Comic Sans",
    description:
      "Laat je skills zien in ons Tetris toernooi. Hoogste score wint.",
  },
  {
    id: 11,
    image: "./Movienight.png",
    date: new Date("2026-09-10T19:00:00"),
    title: "Movie night",
    start_time: "19:00",
    end_time: "23:00",
    type: "cultuur",
    location: "Campus Schoonmeersen",
    description:
      "Filmavond met de vereniging. Gezellig samen kijken en napraten.",
  },
  {
    id: 12,
    image: "./Bowling.png",
    date: new Date("2026-09-22T14:00:00"),
    title: "Bowling",
    start_time: "14:00",
    end_time: "18:00",
    type: "sport",
    location: "O'Learys",
    description: "Bowling activiteit voor alle leden. Fun staat centraal.",
  },
  {
    id: 13,
    image: "./Schaaktoernooi.png",
    date: new Date("2026-10-05T13:00:00"),
    title: "Schaaktoernooi",
    start_time: "13:00",
    end_time: "18:00",
    type: "sport",
    location: "Comic Sans",
    description: "Daag andere leden uit in een spannend schaaktoernooi.",
  },
  {
    id: 14,
    image: "./Tetristoernooi.png",
    date: new Date("2026-10-18T13:00:00"),
    title: "Tetris toernooi",
    start_time: "13:00",
    end_time: "18:00",
    type: "sport",
    location: "Comic Sans",
    description:
      "Competitieve Tetris namiddag met prijzen voor de beste spelers.",
  },
  {
    id: 15,
    image: "./Movienight.png",
    date: new Date("2026-11-02T19:00:00"),
    title: "Movie night",
    start_time: "19:00",
    end_time: "23:00",
    type: "cultuur",
    location: "Campus Schoonmeersen",
    description:
      "Kom langs voor een gezellige filmavond met popcorn en drankjes.",
  },
  {
    id: 16,
    image: "./Bowling.png",
    date: new Date("2026-11-15T14:00:00"),
    title: "Bowling",
    start_time: "14:00",
    end_time: "18:00",
    type: "sport",
    location: "O'Learys",
    description:
      "We sluiten het semester af met een gezellige bowlingnamiddag.",
  },
];

export default events;
